apiVersion: v1
kind: ConfigMap
metadata:
  name: socialecho-config
  namespace: socialecho
data:
  CLIENT_URL: "http://frontend:3000"
  MONGODB_URI: "mongodb://mongodb:27017/db_socialecho"
  PORT: "4000"
  EMAIL_SERVICE: "Gmail"
  PERSPECTIVE_API_DISCOVERY_URL: "https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1"
  TEXTRAZOR_API_URL: "https://api.textrazor.com/"
  INTERFACE_API_URL: "https://api-inference.huggingface.co/models/facebook/bart-large-mnli"
  CLASSIFIER_API_URL: "http://classifier:5000/classify"
