apiVersion: v1
kind: Secret
metadata:
  name: socialecho-secrets
  namespace: socialecho
type: Opaque
data:
  SECRET: "YmFzZTY0ZW5jb2RlZHZhbHVl"  # Replace with actual base64 encoded value
  REFRESH_SECRET: "YmFzZTY0ZW5jb2RlZHZhbHVl"  # Replace with actual base64 encoded value
  CRYPTO_KEY: "YmFzZTY0ZW5jb2RlZHZhbHVl"  # Replace with actual base64 encoded value
  EMAIL: "YmFzZTY0ZW5jb2RlZHZhbHVl"  # Replace with actual base64 encoded value
  PASSWORD: "YmFzZTY0ZW5jb2RlZHZhbHVl"  # Replace with actual base64 encoded value
  PERSPECTIVE_API_KEY: "YmFzZTY0ZW5jb2RlZHZhbHVl"  # Replace with actual base64 encoded value
  TEXTRAZOR_API_KEY: "YmFzZTY0ZW5jb2RlZHZhbHVl"  # Replace with actual base64 encoded value
  INTERFACE_API_KEY: "YmFzZTY0ZW5jb2RlZHZhbHVl"  # Replace with actual base64 encoded value
